language: php
php:
  - '5.6'
  - '7.0'

before_script: composer require "squizlabs/php_codesniffer=*"
script:
  - php vendor/bin/phpcs --standard=PSR2 Application.php
  - php vendor/bin/phpcs --standard=PSR2 extensions/
  - php vendor/bin/phpcs --standard=PSR2 modules/
  - php vendor/bin/phpcs --standard=PSR2 sources/
  - php vendor/bin/phpcs --standard=PSR2 tasks/
